### ISSUE TITLE
Integration of Phyloscanner.R.utilities functions into phyloscannerR v1.8.0

### ISSUE THREAD

**Issue by magosil86** [olli0601/Phyloscanner.R.utilities#2]
Hi Oliver,

I noted that the `count.pairwise.relationships()` and  `classify.pairwise.relationships()` functions for reconstructing transmission networks have now been integrated into the latest phyloscannerR release (v1.8.0) and was wondering whether there any plans to integrate the `phsc.find.transmission.networks.from.linked.pairs()` and `phsc.plot.most.likely.transmission.chain()` functions as well?

I am asking as the data frames output by `count.pairwise.relationships()` and  `classify.pairwise.relationships()` in phyloscannerR  (v1.8.0) are currently different from the input expected by `phsc.find.transmission.networks.from.linked.pairs()` and `phsc.plot.most.likely.transmission.chain()` in Phyloscanner.R.utilities

Thanks,

**Comment by olli0601** [comment]
Hello

Yes, absolutely. I hope to migrate `phsc.find.transmission.networks.from.linked.pairs() ` later this week, and `phsc.plot.most.likely.transmission.chain()` next week.

Will this timeline work for you?

Best wishes

Oliver

**Comment by magosil86** [comment]
Yes it will, many thanks Oliver!
